controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  robot_state_controller:
    type: robot_state_controller/RobotStateController
    publish_rate: 100

  trigger_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ trigger_joint_motor ]
    velocity:
      joint: trigger_joint
      search_velocity: 3.1415
      vel_threshold: 0.2
      pid: { p: 0.3, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }
  cover_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ cover_joint_motor ]
    velocity:
      joint: cover_joint
      search_velocity: 3
      vel_threshold: 1e-2
      pid: { p: 0.3, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }

  balance_controller:
    type: rm/BalanceController
    left_wheel:
      joint: left_wheel_joint
      pid: { p: 0.6, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    right_wheel:
      joint: right_wheel_joint
      pid: { p: 0.6, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    pid_follow: { p: 7.0, i: 0, d: 0.3, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }

  orientation_controller:
    type: rm_orientation_controller/Controller
    publish_rate: 100
    name: "gimbal_imu"
    frame_source: "odom"
    frame_target: "base_link"

  gimbal_controller:
    type: rm_gimbal_controllers/Controller
    yaw:
      joint: "yaw_joint"
      pid: { p: 13, i: 60, d: 0.8, i_clamp_max: 0.2, i_clamp_min: -0.2, antiwindup: true, publish_state: true }
      k_chassis_vel: 0.03
    pitch:
      joint: "pitch_joint"
      pid: { p: 4.2, i: 30.0, d: 0.2, i_clamp_max: 0.2, i_clamp_min: -0.2, antiwindup: true, publish_state: true }
    chassis_vel:
      num_data: 20
      debug: true
    imu_name: "gimbal_imu"
    feedforward:
      gravity: 9.5316
      enable_gravity_compensation: false
      mass_origin: [ -0.00242,0.005158,0.02901 ]
    bullet_solver:
      resistance_coff_qd_10: 0.45
      resistance_coff_qd_15: 0.01
      resistance_coff_qd_16: 1.5
      resistance_coff_qd_18: 0.55
      resistance_coff_qd_30: 0.01
      g: 9.81
      delay: 0.06
      dt: 0.001
      timeout: 0.001
      publish_rate: 50

  shooter_controller:
    type: rm_shooter_controllers/Controller
    publish_rate: 50
    friction_left:
      left_friction_wheel:
        joint: "left_friction_wheel_joint"
        pid: { p: 0.0005, i: 0.005, d: 0.0, i_clamp_max: 0.01, i_clamp_min: -0.01, antiwindup: true, publish_state: true }
    friction_right:
      right_friction_wheel:
        joint: "right_friction_wheel_joint"
        pid: { p: 0.0005, i: 0.005, d: 0.0, i_clamp_max: 0.01, i_clamp_min: -0.01, antiwindup: true, publish_state: true }
    trigger:
      joint: "trigger_joint"
      pid: { p: 30.0, i: 0.0, d: 1.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true, publish_state: true }
    push_per_rotation: 8
    push_qd_threshold: 0.90
    forward_push_threshold: 0.22
    exit_push_threshold: 0.25
    block_effort: 0.88
    block_speed: 0.1
    block_duration: 0.05
    block_overtime: 0.5
    anti_block_angle: 0.2
    anti_block_threshold: 0.1
