controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  robot_state_controller:
    type: robot_state_controller/RobotStateController
    publish_rate: 100

  leg_rf_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ right_front_leg_joint_motor ]
    velocity:
      joint: right_front_first_leg_joint
      search_velocity: -1.4
      vel_threshold: 0.05
      pid: { p: 2.0, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }

  leg_lf_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ left_front_leg_joint_motor ]
    velocity:
      joint: left_front_first_leg_joint
      search_velocity: -1.4
      vel_threshold: 0.05
      pid: { p: 2.0, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }

  leg_lb_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ left_back_leg_joint_motor ]
    velocity:
      joint: left_back_first_leg_joint
      search_velocity: 1.4
      vel_threshold: 0.05
      pid: { p: 2.0, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }

  leg_rb_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ right_back_leg_joint_motor ]
    velocity:
      joint: right_back_first_leg_joint
      search_velocity: 1.4
      vel_threshold: 0.05
      pid: { p: 2.0, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }

  four_link_vmc_controller:
    type: rm/VMCController
    left_joint: right_front_first_leg_joint
    right_joint: right_back_first_leg_joint
    vmc_bias_angle: 3.49
    pid_angle: { p: 30, i: 0, d: 2, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    pid_length: { p: 400.0, i: 2, d: 20, i_clamp_max: 40.0, i_clamp_min: -40.0, antiwindup: true, publish_state: true }

  legged_balance_controller:
    type: rm/LeggedBalanceController
    left_wheel:
      joint: left_wheel_joint
      pid: { p: 0.6, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    right_wheel:
      joint: right_wheel_joint
      pid: { p: 0.6, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    pid_follow: { p: 7.0, i: 0, d: 0.3, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    pid_left_leg: { p: 250.0, i: 10, d: 70, i_clamp_max: 30.0, i_clamp_min: -30.0, antiwindup: true, publish_state: true }
    pid_right_leg: { p: 250.0, i: 10, d: 70, i_clamp_max: 30.0, i_clamp_min: -30.0, antiwindup: true, publish_state: true }
    pid_theta_diff: { p: 50.0, i: 0.0, d: 0.01, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    pid_roll: { p: 150.0, i: 10, d: 25, i_clamp_max: 15.0, i_clamp_min: -15.0, antiwindup: true, publish_state: true }
    pid_center_gravity: { p: 0.0, i: 0, d: 0, i_clamp_max: 0.0, i_clamp_min: -0.0, antiwindup: true, publish_state: true }
    pid_length_diff: { p: 30.0, i: 0, d: 0, i_clamp_max: 0.0, i_clamp_min: -0.0, antiwindup: true, publish_state: true }
    leg_protect_angle: 0.9  #0.9
    pitch_protect_angle: 1.1 #1.1
    roll_protect_angle: 1.0
    leg_protect_length: 0.1
    ground_support_threshold: 5
    vmc_bias_angle: 3.49

    gravity_compensation_vel_threshold: 0.1
    gravity_compensation_pos_threshold: 0.5

    jump_over_time: 2.0
    p1: -241100
    p2: 170300
    p3: 39310
    p4: 3234

  orientation_controller:
    type: rm_orientation_controller/Controller
    publish_rate: 100
    name: "gimbal_imu"
    frame_source: "odom"
    frame_target: "base_link"

  gimbal_controller:
    type: rm_gimbal_controllers/Controller
    yaw:
      joint: "yaw_joint"
      pid: { p: 13, i: 0, d: 0.8, i_clamp_max: 0.3, i_clamp_min: -0.3, antiwindup: true, publish_state: true }
      k_chassis_vel: 0.03
    pitch:
      joint: "pitch_joint"
      pid: { p: 5.0, i: 0, d: 0.15, i_clamp_max: 0, i_clamp_min: 0, antiwindup: true, publish_state: true }
      k_v: 0.0
    chassis_vel:
      num_data: 20
      debug: true
    imu_name: "gimbal_imu"
    feedforward:
      gravity: 8.05
      enable_gravity_compensation: false
      mass_origin: [ 0.0,0.005158,0.02901 ]
    bullet_solver:
      resistance_coff_qd_10: 0.45
      resistance_coff_qd_15: 0.01
      resistance_coff_qd_16: 1.5
      resistance_coff_qd_18: 0.55
      resistance_coff_qd_30: 0.01
      g: 9.81
      delay: 0.06
      dt: 0.001
      timeout: 0.001
      publish_rate: 50