rm_manual:
  robot_type: "engineer"
  auto_exchange:
    auto_find:
      yaw:
        range: [ -0.2,0.2 ]
        max_scale: 0.2
        near_tolerance: 0.03
      pitch:
        range: [ -0.05,0.10 ]
        max_scale: 0.9
        near_tolerance: 0.03
      search_range: 1
      time_out: 3
    auto_pre_adjust:
      x:
        max_vel: 0.2
        start_vel: 0.08
        tolerance: 1e10
        offset_refer_exchanger: 0.80
        pid: { p: 0.6, i: 0.2, d: 0., i_clamp_max: 0.2, i_clamp_min: -0.2, antiwindup: true, publish_state: true }
      y:
        max_vel: 0.2
        start_vel: 0.05
        tolerance: 1e10
        offset_refer_exchanger: 0.
        pid: { p: 0.6, i: 0.2, d: 0., i_clamp_max: 0.1, i_clamp_min: -0.1, antiwindup: true, publish_state: true }
      yaw:
        max_vel: 0.25
        start_vel: 0.1
        tolerance: 1e10
        offset_refer_exchanger: 0.3
        pid: { p: 3.0, i: 0., d: 0., i_clamp_max: 0.2, i_clamp_min: -0.2, antiwindup: true, publish_state: true }
      time_out: 4.
      internal_time_out: [ 1., 1., 1., 1. ]
    auto_servo_move:
      x:
        tolerance: 0.02
        offset_refer_exchanger: 0.04
        pid: { p: 5.0, i: 0., d: 0., i_clamp_max: 0.1, i_clamp_min: -0.1, antiwindup: true, publish_state: true }
      y:
        tolerance: 0.1
        offset_refer_exchanger: 0.05
        pid: { p: 6.0, i: 0., d: 0.0, i_clamp_max: 0., i_clamp_min: 0., antiwindup: true, publish_state: true }
      re_y:
        tolerance: 0.005
        offset_refer_exchanger: 0.03
        pid: { p: 10.0, i: 0.0, d: 0.0, i_clamp_max: 2., i_clamp_min: -2., antiwindup: true, publish_state: true }
      z:
        tolerance: 0.2
        offset_refer_exchanger: -0.04
        pid: { p: 7.0, i: 0., d: 0.0, i_clamp_max: 0., i_clamp_min: 0., antiwindup: true, publish_state: true }
      re_z:
        tolerance: 0.001
        offset_refer_exchanger: -0.02
        pid: { p: 8.0, i: 0.0, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true, publish_state: true }
      roll:
        tolerance: 0.005
        offset_refer_exchanger: 1.
        pid: { p: 2.0, i: 0., d: 0., i_clamp_max: 0.5, i_clamp_min: -0.5, antiwindup: true, publish_state: true }
      pitch:
        offset_refer_exchanger: 1.
        pid: { p: 2.0, i: 0.0, d: 0.0, i_clamp_max: 0, i_clamp_min: 0, antiwindup: true, publish_state: true }
      yaw:
        offset_refer_exchanger: 1.
        tolerance: 0.005
        pid: { p: 2.0, i: 0.01, d: 0.0, i_clamp_max: 0.01, i_clamp_min: -0.01, antiwindup: true, publish_state: true }
      link7_length: 0.1
      time_out: 20.
      internal_time_out: [ 1., 2., 2., 2., 2., 4., 4., 5., 1. ]
    union_move:
      x:
        tolerance: 0.005
        offset_refer_exchanger: 0.
        pid: { p: 5.0, i: 0., d: 0., i_clamp_max: 0.1, i_clamp_min: -0.1, antiwindup: true, publish_state: true }
      y:
        tolerance: 0.005
        offset_refer_exchanger: 0.023
        pid: { p: 10.0, i: 0., d: 0.0, i_clamp_max: 2., i_clamp_min: -2., antiwindup: true, publish_state: true }
      z:
        tolerance: 0.2
        offset_refer_exchanger: -0.02
        pid: { p: 4.0, i: 0.0, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true, publish_state: true }
      motion_name:  "EXCHANGE_SPHERE"
      time_out: 10.
      internal_time_out: [ 3., 3., 4., 3., 1.]
    time_out: 15.
  joint_limit:
    joint1: [0.,0.45]
    joint2: [0.,0.81]
    joint3: [-0.28,0.33]
    joint_offset: [ 0.185, 0., 0. ]

  chassis:
    topic: "/cmd_chassis"
    accel_x:
      - [ 200.0,8. ]
    accel_y:
      - [ 200.0,8. ]
    accel_z:
      - [ 200.0,30. ]
    safety_power: 400
    capacitor_threshold: 0.1
    charge_power: 0
    extra_power: 5000
    burst_power: 999
    buffer_threshold: 10
    power_gain: 0.85
    speed_scale: 0.8

    fast_speed_scale: 1.1
    normal_speed_scale: 0.8
    low_speed_scale: 0.2
    exchange_speed_scale: 0.15

    fast_gyro_scale: 1.5
    normal_gyro_scale: 0.8
    low_gyro_scale: 0.4
    exchange_gyro_scale: 0.2

  vel:
    topic: "/cmd_vel"
    max_linear_x:
      - [ 50.0,3. ]
      - [ 80.0,3. ]
      - [ 200.0,3. ]
    max_linear_y:
      - [ 50.0,3. ]
      - [ 80.0,3. ]
      - [ 200.0,3. ]
    max_angular_z:
      - [ 50.0,3. ]
      - [ 80.0,3. ]
      - [ 200.0,3. ]
    gyro_move_reduction: 1
    gyro_rotate_reduction: 1
  servo:
    topic: "/servo_server/delta_twist_cmds"
    max_linear_x: 0.4
    max_linear_y: 0.4
    max_linear_z: 0.4
    max_angular_x: 1.3
    max_angular_y: 1.3
    max_angular_z: 2.5
  gimbal:
    topic: "/controllers/gimbal_controller/command"
    max_yaw_vel: 2.5
    max_pitch_vel: 1
    track_timeout: 0.5
    target_cost_function:
      k_pos: 1.0
      k_vel: 1.0
      k_hp: 1.0
      k_freq: 1.0
      timeout: 0.0



  chassis_calibrate_motor: [ ]
  gimbal_calibrate_motor: [ ]
  shooter_calibrate_motor: [ ]

  controllers_list:
    state_controllers:
      - controllers/robot_state_controller
      - controllers/joint_state_controller
    main_controllers:
      - controllers/arm_trajectory_controller
      - controllers/chassis_controller
      - controllers/gimbal_controller
      - controllers/gpio_controller
      - controllers/mimic_joint1_controller
      - controllers/ore_bin_lifter_controller
      - controllers/ore_bin_rotate_controller
      - controllers/gimbal_lifter_controller
#      - controllers/extend_arm_a_controller
#      - controllers/extend_arm_b_controller

    calibration_controllers:
#      - controllers/pitch_calibration_controller
      - controllers/joint1_calibration_controller
      - controllers/joint2_calibration_controller
      - controllers/joint3_calibration_controller
      - controllers/joint4_calibration_controller
      - controllers/joint5_calibration_controller
      - controllers/joint6_calibration_controller
      - controllers/joint7_calibration_controller
      - controllers/mimic_joint1_calibration_controller
      - controllers/ore_bin_lifter_calibration_controller
      - controllers/gimbal_lifter_calibration_controller
#      - controllers/extend_arm_a_calibration_controller
#      - controllers/extend_arm_b_calibration_controller


  pitch_calibration:
    - start_controllers:
        - controllers/pitch_calibration_controller
      stop_controllers:
        - controllers/gimbal_controller
      services_name:
        - /controllers/pitch_calibration_controller/is_calibrated

  calibration_gather:
    - start_controllers:
        - controllers/mimic_joint1_calibration_controller
        - controllers/joint1_calibration_controller
        - controllers/joint3_calibration_controller
        - controllers/joint4_calibration_controller
        - controllers/joint7_calibration_controller
        - controllers/joint5_calibration_controller
        - controllers/joint6_calibration_controller
#        - controllers/pitch_calibration_controller
        - controllers/ore_bin_lifter_calibration_controller
        - controllers/gimbal_lifter_calibration_controller
#        - controllers/extend_arm_a_calibration_controller
#        - controllers/extend_arm_b_calibration_controller
      stop_controllers:
        - controllers/mimic_joint1_controller
        - controllers/gimbal_controller
        - controllers/arm_trajectory_controller
        - controllers/ore_bin_lifter_controller
        - controllers/gimbal_lifter_controller
#        - controllers/extend_arm_a_controller
#        - controllers/extend_arm_b_controller
      services_name:
        - /controllers/mimic_joint1_calibration_controller/is_calibrated
        - /controllers/joint1_calibration_controller/is_calibrated
        - /controllers/joint3_calibration_controller/is_calibrated
        - /controllers/joint4_calibration_controller/is_calibrated
        - /controllers/joint5_calibration_controller/is_calibrated
        - /controllers/joint6_calibration_controller/is_calibrated
        - /controllers/joint7_calibration_controller/is_calibrated
#        - /controllers/pitch_calibration_controller/is_calibrated
        - /controllers/ore_bin_lifter_calibration_controller/is_calibrated
        - /controllers/gimbal_lifter_calibration_controller/is_calibrated
#        - controllers/extend_arm_a_calibration_controller/is_calibrated
#        - controllers/extend_arm_b_calibration_controller/is_calibrated

    - start_controllers:
        - controllers/joint2_calibration_controller
      stop_controllers:
        - controllers/arm_trajectory_controller
      services_name:
        - /controllers/joint2_calibration_controller/is_calibrated
