rm_referee:
  robot_type: standard
  send_ui_queue_delay: 0.10
  add_ui_frequency: 0.5
  add_ui_max_times: 3
  dbus_topic: "/rm_ecat_hw/dbus"
  ui:
    trigger_change:
      - name: "chassis"
        config: { start_position: [ 100, 850 ], size: 15, width: 2, title: "chassis: " }
      - name: "gimbal"
        config: { start_position: [ 100, 800 ], size: 15, width: 2, title: "gimbal:  " }
      - name: "shooter"
        config: { start_position: [ 100, 750 ], size: 15, width: 2, title: "shooter: " }
      - name: "target"
        config: { start_position: [ 100, 700 ], size: 15, width: 2, title: "target: " }
      - name: "target_view_angle"
        config: { type: "rectangle", start_position: [ 500, 240 ], end_position: [ 1420,840 ], width: 3 }
    time_change:
      - name: "bullet"
        config: { type: "int_num", start_position: [ 170, 560 ], size: 30, width: 3 , delay: 0.4 }
      - name: "capacitor"
        config: { type: "line", width: 5, delay: 0.5,
                  start_position: [ 610, 100 ], end_position: [ 1210, 100 ] }
      - name: "lane_line"
        config: { type: "line", width: 4, color: "cyan", delay: 0.15,
                  start_position: [ 800, 1080 ], end_position: [ 800, 600 ] }
        data: { radius: 0.235, height: 0.4, camera_range: 0.8, surface_coefficient: 0.55 }
        reference_frame: "pitch"
      - name: "rotation"
        config: { type: "arc", width: 7, delay: 0.15, color: "yellow",
                  start_position: [ 960, 520 ], end_position: [ 320, 320 ] , start_angle: 60, end_angle: 120 }
        data: { scale: 50, gimbal_reference_frame: "yaw", chassis_reference_frame: "base_link" }
      - name: "target_distance"
        config: { type: "float_num", start_position: [ 190, 650 ], size: 25, width: 3 ,color: "yellow", delay: 0.4 }
    fixed:
      - name: "capacity_boundary_l"
        config: { type: "line", width: 2, color: "green",
                  start_position: [ 610, 110 ], end_position: [ 610, 90 ] }
      - name: "capacity_boundary_r"
        config: { type: "line", width: 2, color: "green",
                  start_position: [ 1210, 110 ], end_position: [ 1210, 90 ] }
      - name: "2m"
        config: { type: "line", width: 2, color: "yellow",
                  start_position: [ 925, 435 ], end_position: [ 995, 435 ] }
      - name: "3m"
        config: { type: "line", width: 2, color: "yellow",
                  start_position: [ 935, 420 ], end_position: [ 985, 420 ] }
      - name: "5m"
        config: { type: "line", width: 2, color: "yellow",
                  start_position: [ 948, 400 ], end_position: [ 972, 400 ] }
      - name: "mid"
        config: { type: "line", width: 2, color: "yellow",
                  start_position: [ 960, 400 ], end_position: [ 960, 540 ] }
      - name: "target"
        config: { type: "string", start_position: [ 30, 650 ], size: 25, width: 2, color: "pink", content: "target:" }
      - name: "bullet_string"
        config: { type: "string", start_position: [ 30, 600 ], size: 25, width: 2, color: "pink", content: "BULLET:" }
      - name: "max_bullet"
        config: { type: "string", start_position: [ 30, 560 ], size: 30, width: 3, color: "pink", content: "500/" }

    flash:
      - name: "cover"
        config: { start_position: [ 830, 700 ], size: 25, width: 2,
                  color: "green", content: "cover open!!", delay: 0.4 }
      - name: "ore"
        config: { start_position: [ 960, 720 ], size: 15, width: 2,
                  color: "yellow", content: "Ore will released after 10s", delay: 0.4 }
      - name: "armor0"
        config: { type: "circle", width: 3, radius: 50, color: "yellow", delay: 0.75 }
      - name: "armor1"
        config: { type: "circle", width: 3, radius: 50, color: "yellow", delay: 0.75 }
      - name: "armor2"
        config: { type: "circle", width: 3, radius: 50, color: "yellow", delay: 0.75 }
      - name: "armor3"
        config: { type: "circle", width: 3, radius: 50, color: "yellow", delay: 0.75 }
