rm_hw:
  bus:
    - can0
    - can1
    - can2
    - can3

  loop_frequency: 1000
  cycle_time_error_threshold: 0.001
  thread_priority: 95
  # Configurations of the actuators
  actuators:
    #   can0
    #   - reversal
    pitch_front_joint_motor:
      bus: can0
      id: 0x201
      type: rm_2006
      lp_cutoff_frequency: 20
      need_calibration: false
    pitch_behind_joint_motor:
      bus: can0
      id: 0x202
      type: rm_2006
      lp_cutoff_frequency: 20
      need_calibration: false
    roll_left_joint_motor:
      bus: can0
      id: 0x203
      type: rm_2006
      lp_cutoff_frequency: 20
      need_calibration: false
    roll_right_joint_motor:
      bus: can0
      id: 0x204
      type: rm_2006
      lp_cutoff_frequency: 20
      need_calibration: false
    #   can1
    #   - arm
    #      - joint1
    #      - joint2
    #   - gimbal
    joint1_motor:
      bus: can1
      id: 0x201
      type: rm_3508
      need_calibration: true
    #    mimic_joint1_motor:
    #      bus: can1
    #      id: 0x204
    #      type: rm_3508
    #      need_calibration: true
    joint2_motor:
      bus: can1
      id: 0x202
      type: rm_3508
      need_calibration: true
    yaw_joint_motor:
      bus: can1
      id: 0x206
      type: rm_6020
    pitch_joint_motor:
      bus: can1
      id: 0x203
      type: rm_3508
      need_calibration: true
    #   can2
    #   - arm
    #    - joint3
    #    - joint4
    #    - joint5
    #    - joint6
    #    - joint7
    joint3_motor:
      bus: can2
      id: 0x203
      type: rm_3508
      need_calibration: true
    joint4_motor:
      bus: can2
      id: 0x204
      type: rm_3508
      need_calibration: true
    joint5_motor:
      bus: can2
      id: 0x205
      type: rm_3508
      need_calibration: true
    joint6_motor:
      bus: can2
      id: 0x206
      type: rm_3508
      need_calibration: true
    joint7_motor:
      bus: can2
      id: 0x201
      type: rm_2006
      need_calibration: true

    #  can3
    #  - chassis
    #  - drag
    left_front_wheel_motor:
      bus: can3
      id: 0x201
      type: rm_3508
      lp_cutoff_frequency: 150
    left_back_wheel_motor:
      bus: can3
      id: 0x202
      type: rm_3508
      lp_cutoff_frequency: 150
    right_back_wheel_motor:
      bus: can3
      id: 0x203
      type: rm_3508
      lp_cutoff_frequency: 150
    right_front_wheel_motor:
      bus: can3
      id: 0x204
      type: rm_3508
      lp_cutoff_frequency: 150

    drag_joint_motor:
      bus: can3
      id: 0x205
      type: rm_2006
      need_calibration: true

    mimic_drag_joint_motor:
      bus: can3
      id: 0x206
      type: rm_2006
      need_calibration: true

  imus:
    gimbal_imu:
      frame_id: gimbal_imu
      bus: can0
      id: 0x121
      orientation_covariance_diagonal: [ 0.0012, 0.0012, 0.0012 ]
      angular_velocity_covariance: [ 0.0004, 0.0004, 0.0004 ]
      linear_acceleration_covariance: [ 0.01, 0.01, 0.01 ]
      angular_vel_coeff: 0.0010652644
      accel_coeff: 0.0017944335
      temp_coeff: 0.125
      temp_offset: 23.0
      filter: complementary
      do_bias_estimation: false
      do_adaptive_gain: true
      gain_acc: 0.0003
  gpios:
    gripper:
      pin: 657
      direction: out